### ISSUE TITLE
Divisibility test

### ISSUE THREAD

**Issue by coder-cat-999** [coding-ninja-23/C-solution#18]
# Enter your question -
C program to check divisibility of any number by any number (user defined)

# Tags for the question(eg - Array, Basic, Stack, etc.) -
Basic

**Comment by coder-cat-999** [comment]
Kindly add the label "WithSolution".

**Comment by coding-ninja-23** [comment]
@coder-cat-999  What is the status of this issue?
Please submit the solution by 14 Oct'21 otherwise this issue would be assigned to @juitelavane
