### ISSUE TITLE
Prime Numbers 

### ISSUE THREAD

**Issue by coding-ninja-23** [coding-ninja-23/C-solution#26]
# Enter your question -
Take input from users the range and then print all the prime numbers within that range. Also print the total number of print numbers. 

Example of output :

Enter the range: 
0 (user entered)
10 (user entered)

Prime numbers in the given range are: 2 3 5 7 
There are 4 prime numbers in the given range.

# Tags for the question(eg - Array, Basic, Stack, etc.) -
Basic, loop

**Comment by smily31** [comment]
Ok I will create
