### ISSUE TITLE
Sorting and Searching

### ISSUE THREAD

**Issue by thesurojit-das** [coding-ninja-23/C-solution#44]
# Enter your question - 
Sort the elements of an array  in ascending order using Linear Search in Array SORT technique

# Tags for the question(eg - Array, Basic, Stack, etc.) -
 Array

**Comment by coding-ninja-23** [comment]
Place your solution in "Solutions" folder and do refer the PR_TEMPLATE.md while creating the PR.

**Comment by coding-ninja-23** [comment]
@thesurojit-das What is the status of this issue? 
Please submit the solution by 14 Oct'21 otherwise this issue would be assigned to @impulse15

**Comment by coding-ninja-23** [comment]
@thesurojit-das You were unable to complete the task in given time. Hence this issue is being assigned to @impulse15

**Comment by impulse15** [comment]
I have created a PR , plz review it. Thanks
